graph TB
	aaa["开始"]
	subgraph 油田小循环
	aab["油田小循环串联输入"]
	subgraph 3x精炼站_聚合树脂
	aac["3x精炼站_聚合树脂并联输入"]
	aad["精炼站_聚合树脂"]
	aac-->|"电力(30MW),原油(60m³)"|aad
	aae["精炼站_聚合树脂"]
	aac-->|"电力(30MW),原油(60m³)"|aae
	aaf["精炼站_聚合树脂"]
	aac-->|"电力(30MW),原油(60m³)"|aaf
	aag["3x精炼站_聚合树脂并联输出"]
	aad-->|"聚合树脂(130),重油残渣(20m³)"|aag
	aae-->|"聚合树脂(130),重油残渣(20m³)"|aag
	aaf-->|"聚合树脂(130),重油残渣(20m³)"|aag
	end
	aab-->|"原油(180m³)"|aac
	subgraph 精炼产物消耗
	aah["精炼产物消耗并联输入"]
	subgraph 副产物发电
	aai["副产物发电串联输入"]
	aaj["精炼站_残渣燃料油"]
	aai-->|"电力(30MW),重油残渣(60m³)"|aaj
	subgraph 2x燃油发电机
	aak["2x燃油发电机并联输入"]
	aal["燃油发电机"]
	aak-->|"燃料(20)"|aal
	aam["燃油发电机"]
	aak-->|"燃料(20)"|aam
	aan["2x燃油发电机并联输出"]
	aal-->|"电力(250MW)"|aan
	aam-->|"电力(250MW)"|aan
	end
	aaj-->|"燃料(40)"|aak
	aao["副产物发电串联输出"]
	aan-->|"电力(500MW)"|aao
	end
	aah-->|"重油残渣(60m³)"|aai
	subgraph 塑料产出
	aap["塑料产出串联输入"]
	subgraph 塑料输入
	aaq["塑料输入并联输入"]
	aar["聚合树脂缓冲"]
	aaq-->|"聚合树脂(390)"|aar
	aas["抽水站"]
	aaq-->|"电力(20MW)"|aas
	aat["塑料输入并联输出"]
	aar-->|"聚合树脂(390)"|aat
	aas-->|"水(120m³)"|aat
	end
	aap-->|"聚合树脂(390)"|aaq
	subgraph 6x精炼站_聚合塑料
	aau["6x精炼站_聚合塑料并联输入"]
	aav["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aav
	aaw["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aaw
	aax["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aax
	aay["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aay
	aaz["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aaz
	aba["精炼站_聚合塑料"]
	aau-->|"电力(30MW),聚合树脂(60),水(20m³)"|aba
	abb["6x精炼站_聚合塑料并联输出"]
	aav-->|"塑料(20)"|abb
	aaw-->|"塑料(20)"|abb
	aax-->|"塑料(20)"|abb
	aay-->|"塑料(20)"|abb
	aaz-->|"塑料(20)"|abb
	aba-->|"塑料(20)"|abb
	end
	aat-->|"水(120m³),聚合树脂(360)"|aau
	abc["塑料产出串联输出"]
	abb-->|"塑料(120),聚合树脂(30)"|abc
	end
	aah-->|"聚合树脂(390)"|aap
	abd["精炼产物消耗并联输出"]
	aao-->|"电力(500MW)"|abd
	abc-->|"塑料(120),聚合树脂(30)"|abd
	end
	aag-->|"聚合树脂(390),重油残渣(60m³)"|aah
	abe["油田小循环串联输出"]
	abd-->|"塑料(120),电力(500MW),聚合树脂(30)"|abe
	end
	aaa-->|"原油(180m³)"|aab